version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs_app_literal_cafe
    ports:
      - "3001:3000"  # Порт для обращения к контейнеру

    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production



